[package]
edition = "2021"
name = "bandwhich"
description = "Display current network utilization by process, connection and remote IP/hostname"
version = "0.20.0"
homepage = "https://github.com/imsnif/bandwhich"
repository = "https://github.com/imsnif/bandwhich"
readme = "README.md"
authors = [
       "Aram Drevekenin <aram@poor.dev>",
       "Eduardo Toledo <etoledom@icloud.com>",
       "Eduardo Broto <ebroto@tutanota.com>",
       "Kelvin Zhang <zhangxp1998@gmail.com>",
       "Brooks Rady <b.j.rady@gmail.com>",
]
keywords = ["networking", "utilization", "cli"]
categories = ["network-programming", "command-line-utilities"]
license = "MIT"
exclude = ["src/tests/*", "demo.gif"]

[dependencies]
pnet = "0.33.0"
ipnetwork = "0.20.0"
tui = { version = "0.19", default-features = false, features = ["crossterm"] }
crossterm = "0.26.0"                                                           #
structopt = "0.3"
chrono = "0.4"
regex = "1.7.1"
lazy_static = "1.4.0"
tokio = { version = "1.26", features = ["rt", "sync"] }
trust-dns-resolver = "0.22.0"
async-trait = "0.1.64"
unicode-width = "0.1.10"
#resolv-conf = "0.7.0"
parking_lot = "0.12.1"
anyhow = "1.0.71"
thiserror = "1.0.40"

[profile.release]
lto = true

[target.'cfg(target_os="windows")'.dependencies]
netstat2 = "0.9.1"
sysinfo = "0.28.0"

[target.'cfg(target_os="linux")'.dependencies]
procfs = "0.15.1"

[dev-dependencies]
insta = "1.28.0"
pnet_base = "0.33.0"
cargo-insta = "1.28.0"
packet-builder = "0.7.0"
regex = "1"

[target.'cfg(target_os="windows")'.build-dependencies]
http_req = "0.9.0"
zip = "0.6.4"

#[patch.crates-io]
#resolv-conf = { git = 'https://github.com/tailhook/resolv-conf', rev = '83c0f25ebcb0615550488692c5213ca1ae4acd8f' }
